# Generated by Django 4.1.7 on 2023-03-12 00:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'customer',
                'ordering': ['first_name'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField(auto_now=True)),
                ('reserveDate', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('totalPrice', models.PositiveIntegerField(default=0)),
                ('adultTicketCount', models.PositiveIntegerField(default=0)),
                ('ChildTicketCount', models.PositiveIntegerField(default=0)),
                ('FastTrackAdultTicketCount', models.PositiveIntegerField(default=0)),
                ('FastTrackChildTicketCount', models.PositiveIntegerField(default=0)),
                ('SeniorCitizenTicketCount', models.PositiveIntegerField(default=0)),
                ('AdultCollegeIdOfferTicketCount', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumpstart.customer')),
            ],
        ),
    ]
