# Generated by Django 4.1.7 on 2023-03-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='images/gojo.png', upload_to='images/profile/'),
        ),
    ]
