# Generated by Django 4.1.7 on 2023-03-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0002_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='gojo.png', upload_to='images/profile/'),
        ),
    ]
