# Generated by Django 4.1.7 on 2023-03-23 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jumpstart', '0003_alter_customer_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('single', 'Single Event'), ('multi', 'Multi Event')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timings', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('additional_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('S', 'Single Event'), ('M', 'Multi Event')], max_length=1)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('ticket_id', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumpstart.event')),
            ],
        ),
    ]
