# Generated by Django 4.1.7 on 2023-03-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0005_rename_price_ticket_total_price_ticket_adult_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reservation_type',
            field=models.CharField(choices=[('Single Event', 'single-event'), ('Multi Event', 'multi-event')], max_length=12),
        ),
    ]
