# Generated by Django 4.1.7 on 2023-03-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0006_alter_ticket_reservation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='event',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='reservation_type',
            new_name='reserved_event',
        ),
    ]
