# Generated by Django 4.1.7 on 2023-03-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0007_rename_event_ticket_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_type',
            field=models.ForeignKey(db_column='event_type', on_delete=django.db.models.deletion.CASCADE, to='jumpstart.event'),
        ),
    ]
