# Generated by Django 4.1.7 on 2023-03-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0008_alter_ticket_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_type',
            field=models.CharField(choices=[('Single Event', 'single-event'), ('Multi Event', 'multi-event')], max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reserved_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumpstart.event'),
        ),
    ]
