# Generated by Django 4.1.7 on 2023-03-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0009_alter_ticket_event_type_alter_ticket_reserved_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('single', 'single-event'), ('multi', 'multi-event')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_type',
            field=models.CharField(choices=[('single-event', 'Single Event'), ('multi-event', 'Multi Event')], max_length=12),
        ),
    ]
