# Generated by Django 4.1.7 on 2023-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0010_alter_event_event_type_alter_ticket_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reservation_time',
            field=models.CharField(choices=[('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM'), ('18:00', '6:00 PM')], max_length=12),
        ),
    ]
