# Generated by Django 4.1.7 on 2023-03-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0011_alter_ticket_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
