# Generated by Django 4.1.7 on 2023-03-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0012_alter_ticket_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
