# Generated by Django 4.1.7 on 2023-03-25 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0013_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transaction_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 0, 34, 15, 358094, tzinfo=datetime.timezone.utc)),
        ),
    ]
