# Generated by Django 4.1.7 on 2023-03-25 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0014_ticket_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='transaction_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 1, 31, 56, 288535, tzinfo=datetime.timezone.utc)),
        ),
    ]
