# Generated by Django 4.1.7 on 2023-03-26 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0016_remove_customer_user_ptr_customer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='spl_adult_tickets',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='spl_children_tickets',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='profile/gojo.png', upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transaction_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 3, 30, 23, 413391, tzinfo=datetime.timezone.utc)),
        ),
    ]
