# Generated by Django 4.1.7 on 2023-03-26 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0019_event_keywords_alter_ticket_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='transaction_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 13, 46, 52, 930377, tzinfo=datetime.timezone.utc)),
        ),
    ]
